<?php
/**
 * @file
 * hot_tables.module
 */

include_once 'hot_buttons.features.inc';
define('HOT_BUTTONS_PATH', drupal_get_path('module', 'hot_buttons'));

/**
 * Implementation of hook_entity_info_alter()
 */
function hot_buttons_entity_info_alter(&$entity_info){
  // Basic table
  $entity_info['fieldable_panels_pane']['bundles']['hot_buttons'] = array(
    'label' => t('Button'),
    'pane category' => t('Widgets'),
    'pane top level' => FALSE,
    'pane icon' => HOT_BUTTONS_PATH . '/images/icon_button.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hot-buttons',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements  hook_field_collection_item_view().
 * Theme the field  collection like it should be.
 */
function hot_buttons_field_collection_item_view($field_collection_item, $view_mode, $langcode) {
  $content = $field_collection_item->content;
  if($content['#bundle'] == 'field_hot_button'){
    $style = 'btn-default';
    $size = '';
    if(isset($content['field_button_style']['#items'][0]['value'])){
      $style =  $content['field_button_style']['#items'][0]['value'];
      unset($content['field_button_style']);
    }
    if(isset($content['field_button_size']['#items'][0]['value'])){
      $size = $content['field_button_size']['#items'][0]['value'];
      $size .= $size == 'btn-block' ? ' btn-lg' : '';
      unset($content['field_button_size']);
    }
    $content['field_button_link'][0]['#element']['attributes'] = array(
      'class' => implode(' ', array('btn', $style, $size))
    );
    $field_collection_item->content = $content;
  }
}


/**
 * Implements hook_preprocess_panels_pane().
 * Add button groups
 */
function hot_buttons_preprocess_panels_pane($variables){
  if(isset($variables['content']['#bundle']) && $variables['content']['#bundle'] == 'hot_buttons'){
    if(isset($variables['content']['field_hot_button'])){
      $variables['content']['field_hot_button']['theme'] = 'markup';
    }
    if(isset($variables['content']['field_button_group'])){

    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function hot_buttons_theme() {
  $theme_registry['field_collection_item__field_hot_button'] =
    array(
      'template' => 'templates/field-collection-item--field-hot-button',
      'type' => 'module'
    );
  $theme_registry['field__field_hot_button'] =
    array(
      'function' => 'theme_field__field_hot_button',
      'type' => 'module'
    );
  $theme_registry['fieldable_panels_pane__hot_buttons'] =
    array(
      'template' => 'templates/fieldable-panels-pane--hot-buttons',
      'type' => 'module'
    );
  return $theme_registry;

}


function theme_field__field_hot_button(&$variables){
  $output = '';
  foreach ($variables['items'] as $delta => $item) {
    drupal_render($item);
  }
  return $output;
}
