<?php
/**
 * @file
 * hot_tables.module
 */

include_once 'hot_buttons.features.inc';

/**
 * Implementation of hook_entity_info_alter()
 */
function hot_buttons_entity_info_alter(&$entity_info){
  // Basic table
  $entity_info['fieldable_panels_pane']['bundles']['hot_buttons'] = array(
    'label' => t('Button'),
    'pane category' => t('Widgets'),
    'pane top level' => FALSE,
    'pane icon' => drupal_get_path('module', 'hot_buttons') . '/images/icon_button.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hot-buttons',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}


function hot_buttons_field_collection_item_view($field_collection_item, $view_mode, $langcode) {
  $content = $field_collection_item->content;
  if($content['#bundle'] == 'field_hot_button'){
    $style = 'btn-default';
    $size = '';
    if(isset($content['field_button_style']['#items'][0]['value'])){
      $style =  $content['field_button_style']['#items'][0]['value'];
      unset($content['field_button_style']);
    }
    if(isset($content['field_button_size']['#items'][0]['value'])){
      $size = $content['field_button_size']['#items'][0]['value'];
      unset($content['field_button_size']);
    }
    $content['field_button_link'][0]['#element']['attributes'] = array(
      'class' => implode(' ', array('btn', $style, $size)) 
    );
    $field_collection_item->content = $content;
    dpm($field_collection_item);
  }

}
